### ISSUE TITLE
Add options to override default themes

### ISSUE THREAD

**Issue by oknozor** [oknozor/unveil-rs#12]
End users shall be able to override any default css/js files by specifying coresponding path in the project config :

```toml 
default_css = "my_theme.css"
default_js = "myscript.js"
# And so on ...
```
